baseURL: "https://sciencebricks.ai/"
# baseURL: "https://manucalop.github.io/science-bricks/"
title: Science Bricks
paginate: 5
theme: hugo-PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-N7QBCDRCZF

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Science Bricks
  description: Learn Science. One Brick at a Time
  keywords: [Blog, Portfolio, PaperMod]
  # author: Manuel Castillo-Lopez
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "2 January 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  math: true
  hideFooter: true

  ShowFullTextinRSS: false
  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

# copyright: Foo

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: logo.png
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: Science Bricks
    # icon: logo-led.png
    iconHeight: 35

  profileMode:
    enabled: true # needs to be explicitly set
    title: Learn Science
    subtitle: One Brick at a Time
    imageUrl: logo-led.png
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image
    buttons:
      - name: Courses
        url: courses
      - name: Blog
        url: posts
      # - name: Tags
      #   url: tags

  # home-info mode
  homeInfoParams:
    Title: Learn Science
    Content: One Brick at a Time.

  # socialIcons:
  #   - name: linkedin
  #     url: "https://www.linkedin.com/in/manucalop/"
  #   - name: github
  #     url: "https://github.com/manucalop"
  #   - name: email
  #     url: "mailto:manucalop@gmail.com"
  #   - name: googlescholar
  #     url: "https://scholar.google.com/citations?user=yBj-WI4AAAAJ"

   # - name: twitter
   #   url: "https://twitter.com/"
  #   - name: stackoverflow
  #     url: "https://stackoverflow.com"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/manucalop/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: courses
      name: Courses
      url: /courses/
      weight: 10
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 10
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
